import { animetriximg, muxikimg, quibbleimg, recordify, sso, synthiaimg, trimImg, wasteeasy } from "./index";
export const projectArray = [
    {
        name: "Animetrix",
        description: "Anime Trix is a full stack anime streaming / downloading site developed in NEXTJS 13.5 and TYPESCRIPT that offers a vast collection of anime shows for streaming and downloading. With a user-friendly interface, you can easily find your favorite anime shows and watch them in high-definition quality.",
        image: animetriximg,
        type: "open source",
        hostedLink: "https://www.animetrix.xyz/",
        githubLink: "https://www.github.com/shivabhattacharjee/animetrix-next",
    },
    {
        name: "Waste Easy",
        description: "WasteEasy is an app designed to streamline waste management. Developed during the Envision Hackathon, it focuses on waste classification and encourages proper waste segregation. Users can earn points or coupons by utilizing WasteEasy for their waste disposal needs.",
        image: wasteeasy,
        type: "Hackathon Project",
        hostedLink: "https://wasteeasy.theshiva.xyz/",
        githubLink: "https://www.github.com/shivabhattacharjee/wasteeasy",
    },
    {
        name: "SSO-Auth",
        description: "SSO is a Single Sign-On (SSO) system that allows users to seamlessly authenticate across multiple applications using a single set of credentials. Built with Next.js, PostgreSQL, Prisma, and Tailwind CSS, SSO offers a secure and efficient way to manage user authentication",
        image: sso,
        type: "Open Source",
        hostedLink: "http://demosso.theshiva.xyz/",
        githubLink: "https://www.github.com/shivabhattacharjee/sso",
    },
    {
        name: "Trim",
        description: "Trim is a sleek and efficient URL shortener project developed using Next.js .  With Trim, users can easily shorten lengthy URLs into concise, manageable links, making sharing and distributing web addresses more convenient",
        image: trimImg,
        type: "open source",
        hostedLink: "https://trim.theshiva.xyz",
        githubLink: "https://www.github.com/shivabhattacharjee/trim",
    },
    {
        name: "Quibble",
        description: "Quibble, a content generation bot, simplifies and elevates your creative process developed in NEXTJS 14 and TYPESCRIPT. Whether crafting engaging blog posts, soulful song lyrics, or attention-grabbing Insta captions, Quibble's advanced algorithms seamlessly transform your ideas into polished, professional content.",
        image: quibbleimg,
        type: "open source",
        hostedLink: "https://quibble.theshiva.xyz",
        githubLink: "https://www.github.com/shivabhattacharjee/quibble",
    },
    {
        name: "Synthia",
        description: "Synthia is a lightweight and beginner-friendly interpreted programming language developed in Rust. With a simple, intuitive syntax and a focus on ease of use, Synthia is perfect for both newcomers to programming and experienced developers looking for a flexible scripting language",
        image: synthiaimg,
        type: "open source",
        hostedLink: "",
        githubLink: "https://www.github.com/shivabhattacharjee/synthia",
    },
    {
        name: "Recordify",
        description: "Recordify is a chrome extension that allows users to record their screen and audio. It is developed in vanilla JavaScript . Users can record their screen and audio with a single click and save the recording as a webm file.",
        image: recordify,
        type: "open source",
        hostedLink: "",
        githubLink: "https://www.github.com/shivabhattacharjee/recordify",
    },
    {
        name: "Muxik",
        description: "Muxik is a music streaming and downloading platform developed on ReactJs. It provides users with a wide variety of songs, albums, playlists, and artists across different genres. Users can enjoy a seamless and immersive music listening experience through the platform.",
        image: muxikimg,
        type: "open source",
        hostedLink: "",
        githubLink: "https://www.github.com/shivabhattacharjee/muxik",
    },
    {
        name: "Muxik - CURD API",
        description: "Backend API for muxik developed on NodeJs, ExpressJs, and MongoDB. It allows user to register, login, create, read, update, and delete songs, albums, playlists, and artists. It also allows user to upload and delete songs, albums, playlists, and artists.",
        image: muxikimg,
        type: "open source",
        hostedLink: "",
        githubLink: "https://www.github.com/shivabhattacharjee/muxik-backend",
    },
];
