import docker from "./docker.svg";
import postgresssql from "./elephant.png";
import git from "./Git-Icon-1788C.svg";
import go from "./go.svg";
import mongodb from "./mongodb.svg";
import mysql from "./mysql.svg";
import nextjs from "./nextjs-transparent.svg";
import nodejs from "./nodejs.svg";
import python from "./python-logo-only.png";
import react from "./react.svg";
import redis from "./redis-logo-full-color-rgb.svg";
import redux from "./redux.svg";
import rust from "./rust.svg";
import socketio from "./Socket-io.svg";
import tailwind from "./tailwind.svg";
import ts from "./ts.svg";
import vercel from "./vercel.svg";
export { go, git, postgresssql, rust, redis, mongodb, mysql, socketio, nextjs, nodejs, react, redux, tailwind, ts, vercel, docker, python };
